### ISSUE TITLE
How to download the highest resolution as default?

### ISSUE THREAD

**Issue by AlexanderJiazx** [zararashraf/youtube-video-downloader-api#6]
Same as title

**Comment by zararashraf** [comment]
Hi Alexander,

To modify the API so that it downloads the highest resolution available by default, you can modify the download_video function with something like this but be aware that the library prolly does not support audio on and after 1080p.

def download_video(url):
    try:
        yt = YouTube(url)
        # Get the highest resolution stream
        stream = yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first()
        if stream:
            stream.download()
            return True, None
        else:
            return False, "No suitable video stream found."
    except Exception as e:
        return False, str(e)

@app.route('/download', methods=['POST'])
def download_highest_resolution():
    data = request.get_json()
    url = data.get('url')
    
    if not url:
        return jsonify({"error": "Missing 'url' parameter in the request body."}), 400

    if not is_valid_youtube_url(url):
        return jsonify({"error": "Invalid YouTube URL."}), 400
    
    success, error_message = download_video(url)
    
    if success:
        return jsonify({"message": "Video downloaded successfully in the highest resolution."}), 200
    else:
        return jsonify({"error": error_message}), 500

**Comment by AlexanderJiazx** [comment]
Got it, thanks!
